src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommandeRepository::class)
 */
class Commande
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="commandes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $User;

    /**
     * @ORM\Column(type="float")
     */
    private $total;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $statut;

    /**
     * @ORM\OneToMany(targetEntity=ComProduit::class, mappedBy="commande", orphanRemoval=true,cascade={"persist"})
     */
    private $comproduits;

    public function __construct()
    {
        $this->comproduits = new ArrayCollection();
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }


    public function getTotal(): ?float
    {
        return $this->total;
    }

    public function setTotal(float $total): self
    {
        $this->total = $total;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(?\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(?string $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    /**
     * @return Collection<int, Comproduit>
     */
    public function getComproduits(): Collection
    {
        return $this->comproduits;
    }

    public function addComproduit(Comproduit $comproduit): self
    {
        if (!$this->comproduits->contains($comproduit)) {
            $this->comproduits[] = $comproduit;
            $comproduit->setCommande($this);
        }

        return $this;
    }

    public function removeComproduit(Comproduit $comproduit): self
    {
        if ($this->comproduits->removeElement($comproduit)) {
            // set the owning side to null (unless already changed)
            if ($comproduit->getCommande() === $this) {
                $comproduit->setCommande(null);
            }
        }
        return $this;
    }

}

templates/acceuil.html.twig
{% extends "base.html.twig" %}

{% block title %}acceuil{% endblock %}

{% block body %}
  <h1>Page d'acceuil :</h1>
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">  
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
        {# <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> #}
        <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
          <link rel = "stylesheet" href = "{{ asset('/stylesheet/cart.css')}}">
                       <script src="{{asset('/js/app.js')}}"></script>

        {% block stylesheets %}
            {# {{ encore_entry_link_tags('app') }} #}
        {% endblock %}
          
        {% block javascripts %}
            {# {{ encore_entry_script_tags('app') }} #}
     {% endblock %}

        
    </head>
    <body>
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="">Site E-commerce</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" href="{{ path('index')}}">Acceuil</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{{ path('listecategorie') }}">Nos Categories</a>
        </li> 
        
        {% if app.user %}
        <li class="nav-item">
          <a class="nav-link active" href="{{ path('utilisateur')}}">{{app.User.username}}</a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link active" href="{{ path('editer') }}">mon profil</a>
        </li>

        <li class="nav-item">
          <a class="nav-link active" href="{{ path('app_logout') }}">Deconnexion</a>
        </li>

    {% if is_granted('ROLE_ADMIN') %}

      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Gestion
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown2">
            <a class="dropdown-item" href="{{ path('article_') }}">Gestion des Articles</a>
            <a class="dropdown-item" href="{{ path('categorie_') }}">Gestion des Categories</a>
            <a class="dropdown-item" href="{{ path('utilisateurs_') }}">Gestion des Utilisateurs</a>
            <a class="dropdown-item" href="{{ path('commande_') }}">Liste Commande</a>
        </li>
     {% endif %}


   

    {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{{ path('app_login')}}">Connexion </a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{{ path('app_register')}}">Inscription </a>
        </li>
     {% endif %}

     <li class="nav-item mt-2 ml-3 ">
            <div id="cart" class="d-none"> </div>
            <a href="{{ path('panier_') }}" class="cart position-relative d-inline-flex" aria-label="View your shopping cart">
              <i class="fas fa fa-shopping-cart fa-lg"></i>
              <span class="cart-basket d-flex align-items-center justify-content-center">
    {% if app.session.get('nbproduit')    %}
         {{ app.session.get('nbproduit') }}
    {% else %}
          0
    {% endif %}</span></a>
          </li>




      </ul>
    </div>
  </div>
</nav>
<div class="container">
        {% block body %}{% endblock %}
</div>

    </body>
</html>

templates/listecategorie.html.twig
{% extends "base.html.twig" %}

{% block title %}Index{% endblock %}
      
         {% block stylesheets %}
            {# {{ encore_entry_link_tags('app') }} #}
                 <link rel = "stylesheet" href = "{{ asset('/stylesheet/listecategorie.css')}}">

         {% endblock %}
        
         {% block javascripts %}
                    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js
"></script>


        {% endblock %}

{% block body %}
  <div class="container">
    <div class="d-flex justify-content-center align-items-center mt-5"> <button class="btn btn-dark">OUR CATEGORIES</button> </div>
    <div class="d-flex justify-content-center mt-3"> <span class="text text-center">Finding Best Products Now<br> in Your Fingertips</span> </div>
    <div class="row mt-2 g-4">
  {% for categorie in categories%}
  {% if categorie.statut == 'activé'%}
 <div class="col-md-3">
            <div class="card p-1">
                <div class="d-flex justify-content-between align-items-center p-2">
                    <div class="flex-column lh-1 imagename"> <span>{{categorie.nom}}</span>  </div>
                    <div> <a href="{{ path('afficher_produit',{id : categorie.id}) }}"> <img src = "{{asset('/image/categorie/'~categorie.image)}}"  height="100" width="100" /></a> </div>
                </div>
            </div>
</div> 
{% endif %}
  {% endfor %}
    </div>
</div>
{% endblock %}

templates/listecommande.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion des articles{% endblock %}
        
         {% block stylesheets %}
            {# {{ encore_entry_link_tags('app') }} #}
                <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet">
                <link href="https://cdn.datatables.net/1.12.1/css/dataTables.bootstrap5.min.css" rel="stylesheet">
         {% endblock %}
        
{% block body %}
    <h1>Liste de Commande  :</h1>
<hr>
<table id="example" class="table table-striped" style="width:100%">
        <thead>
    <tr>
        <th>user</th>
        <th>produit </th>
        <th>quantite</th>
        <th>prix</th>
        <th>date</th>
        <th>total</th>
        <th>statut</th>
        <th>action</th>
    </tr>
        </thead>
    <tbody>
{% for commande in commandes %}
    <tr>
    <td rowspan=>{{commande.user.username}}</td>
    <td >
       {% for comproduit in commande.comproduits %}
            * {{comproduit.produit.nom}} <br>
        {% endfor %}
    </td>

    <td >
       {% for comproduit in commande.comproduits %}
            {{comproduit.quantite}} <br>
        {% endfor %}
    </td>
    <td >
       {% for comproduit in commande.comproduits %}
            {{comproduit.produit.prix|number_format(3, '.', ',')}} <br>
        {% endfor %}
    </td>
    <td  >{{commande.date|date('d-m-Y')}}</td>          
    <td  >{{commande.total|number_format(3, '.', ',')}} DT</td>
    <td  >{{commande.statut}}</td> 
    <td >
                 <a href="{{ path('commande_editer',{id : commande.id}) }}" class="btn btn-success"> Editer </a> 
    </td>
    </tr>
{% endfor %}
        

        </tbody>
    </table>


{% endblock %}



 {% block javascripts %}
            {# {{ encore_entry_script_tags('app') }}  #}
                    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js" ></script>
                    <script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js" ></script>
                    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
                   <script src="{{asset('/js/modal.js')}}"></script>
                   <script src="{{asset('/js/datatable.js')}}"></script>
 {% endblock %}

templates/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Connexion !{% endblock %}

{% block body %}

    {% if error %}
        <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
    {% endif %}



<form method="post">
    <h1 class="h3 mb-3 font-weight-normal">Login</h1>
    <label for="inputEmail">Email</label>
    <input type="email" value="{{ last_username }}" name="email" id="inputEmail" class="form-control" autocomplete="email" required autofocus>
    <label for="inputPassword">Password</label>
    <input type="password" name="password" id="inputPassword" class="form-control" autocomplete="current-password" required>
    <input type="hidden" name="_csrf_token"  value="{{ csrf_token('authenticate') }}">
    <button class="btn btn-lg btn-primary" type="submit">  Sign in</button>
</form>


{% endblock %}

templates/modification.html.twig
{% extends "base.html.twig" %}
{% block title %}Ajouter{% endblock %}
{% block body %}
    <h1>{{nom}}</h1>
    <tbody>
{{ form(form) }}
    </tbody>
{% endblock %}

templates/user.html.twig
{% extends "base.html.twig" %}

{% block title %}Index{% endblock %}

{% block body %}
<h1>Bonjour {{app.User.username}}</h1>
{% endblock %}


    {# <h1>Nos utilisateur :</h1>
    <table class="table">
    <thead>
    <tr>
        <th>Id</th>
        <th>Username </th>
        <th>Email</th>
    </tr>
    </thead>
    <tbody>
{% for utilisateur in utilisateurs %}
    <tr>
        <td scope="row">{{utilisateur.id}}</td>
        <td>{{utilisateur.username}}</td>
        <td>{{utilisateur.email}}</td>
    </tr>
{% endfor %}
    </tbody>
</table> #}

templates/utilisateurs.html.twig
{% extends "base.html.twig" %}

{% block title %}Index{% endblock %}
      
         {% block stylesheets %}
            {# {{ encore_entry_link_tags('app') }} #}
                <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet">
                <link href="https://cdn.datatables.net/1.12.1/css/dataTables.bootstrap5.min.css" rel="stylesheet">
         {% endblock %}
        
         {% block javascripts %}
            {# {{ encore_entry_script_tags('app') }} #}
                    {# <script src="https://code.jquery.com/jquery-3.5.1.js" ></script> #}
                    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js" ></script>
                    <script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js" ></script>
                    <script >
                    $(document).ready(function () {
                      $('#example').DataTable();
                                });
                    </script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>

<script>
$(document).ready(function () {

    $('.deleteBtn').on('click', function () {
        let removeUrl = $(this).attr('data-remove-url');
        $('.remove_item').attr('data-remove-url', removeUrl);
    });

    $(".remove_item").click(function () {
        let removeUrl = $(this).attr('data-remove-url');
        $.ajax({
            url: removeUrl,
            type: 'POST',
            data: {},
            contentType: 'text',
            success: function(data)
            {
                $('div.modal-content').html(data)
            },
            error: function(jqXHR){
                $('div.modal-content').html(jqXHR.responseText)
            }
        });
    });
});
</script>


        {% endblock %}

{% block body %}
    <h1>Nos utilisateur </h1>
    <a href="{{ path('utilisateurs_ajouter')}}">ajouter client </a>


<table id="example" class="table table-striped" style="width:100%">
        <thead>
    <tr>
        <th>Id</th>
        <th>Username </th>
        <th>Email</th>
        <th>Action</th>
    </tr>
        </thead>
    <tbody>
{% for utilisateur in utilisateurs %}
    <tr>
        <td scope="row">{{utilisateur.id}}</td>
        <td>{{utilisateur.username}}</td>
        <td>{{utilisateur.email}}</td>
         <td>
            <a href="{{ path('utilisateurs_editer',{id : utilisateur.id}) }}" class="btn btn-success" > Editer </a> 
            <a href data-toggle="modal" data-target="#confirmationModal" 
                    data-remove-url="{{ url('utilisateurs_supprimer',{id : utilisateur.id} ) }}"
                     class="btn btn-danger deleteBtn">Supprimer</a>
            <a href="{{ path('utilisateurs_editer_mdp',{id : utilisateur.id}) }}" class="btn btn-info"> Modifier le mot de passe </a>    
        </td> 
    </tr>
    {% endfor %}
        </tbody>
    </table>

    <div class="modal fade" id="confirmationModal" tabindex="-1">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-body">
                        <h4>Suppression</h4>
                        <p>Êtes-vous sûr de vouloir supprimer ce utilisateur ?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" id="btnNo" data-dismiss="modal">
                            <i class="fa fa-ban" aria-hidden="true"></i> Annuler
                        </button>
                        <a href="{{ path('utilisateurs_') }}" class="btn w-sm btn-danger remove_item">Supprimer</a>
                    </div>
                </div>
            </div>
    </div>
{% endblock %}